# Generated by Django 3.2.9 on 2021-11-21 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('received_date', models.DateField(default=datetime.date.today, verbose_name='received date')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='price')),
                ('unit', models.CharField(choices=[('PC', 'шт'), ('KG', 'кг'), ('GM', 'г'), ('LR', 'л'), ('ML', 'мл'), ('PK', 'уп')], default='PC', max_length=2)),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productsapp.vendor', verbose_name='vendor name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
